export const STORE_ACCOUNT_SELECTED = 'STORE_ACCOUNT_SELECTED';
export const STORE_ADDRESSBOOKS = 'STORE_ADDRESSBOOKS';
export const STORE_SETTING_LANG = 'STORE_SETTING_LANG';
export const STORE_SETTING_ENDPOINT = 'STORE_SETTING_ENDPOINT';
export const STORE_SETTING_CUSTOM_ENDPOINTS = 'STORE_SETTING_CUSTOM_ENDPOINTS';
